name: spell-check
on:
  - push
jobs:
  spell-check:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - uses: actions/checkout@master
      - run: npm install -g cspell
      - run: cspell **/*.md
