name: spell-check
on:
  - push
jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@master
        with:
          files: "**/*.md"
